### ISSUE TITLE
EyesGuard does not work in Windows 7

### ISSUE THREAD

**Issue by ExplorerOL** [0xaryan/EyesGuard#25]
**Description**
It is unable to download EyesGuard from Microsoft Store if you use Windows 7. Also EyesGuard does not run in Windows 7 if you try to build it in Windows 7 or Windows 2008 Server.

**Feature Domain**
Plase check any of the checkbox that is related to your request:

- [ ] UI/UX Improvement
- [ ] Avoid people from making mistake
- [ ] Creativity
- [ ] New fucntionality
- [x] Extend support

**Screenshots**
No Screenshots

**Additional context**

**Comment by 0xaryan** [comment]
Supporting Windows 7 is not in the feature domain of this project. Read #26 for more information.
